/**
 * Literal-value secret backend. URI shape `literal:<value>` returns `<value>`
 * verbatim. Used by CLI-managed subscriptions where the secret IS the
 * authoritative artifact (it was generated by `opensquid webhooks subscribe`
 * and stored inline in `webhooks.yaml`). Production deployments typically
 * prefer `env:` / `op:` / `keychain:` instead, but the CLI's rotate path
 * needs an atomic "write new secret to webhooks.yaml BEFORE invalidating
 * old" guarantee, which only inline storage provides.
 *
 * Empty literal (`literal:`) resolves to null so a malformed URI surfaces
 * via the loader's missing-secret error path instead of silently providing
 * an empty HMAC key.
 *
 * Imports from: ../types.js.
 * Imported by: src/secrets/index.ts.
 */

import type { SecretBackend } from '../types.js';

export function literalBackend(): SecretBackend {
  return {
    scheme: 'literal',
    async resolve(ref: string): Promise<string | null> {
      return Promise.resolve(ref.length > 0 ? ref : null);
    },
  };
}
