/**
 * Unit test for `scripts/emit-schemas.ts`.
 *
 * Two things are verified end-to-end:
 *
 *   1. `emitSchemas` writes all six expected files (one per pack-config YAML).
 *   2. Each emitted JSON Schema, fed to AJV, validates representative
 *      positive + negative samples — proving the schema is shape-correct,
 *      not just well-formed JSON.
 *
 * Why AJV (not Zod re-parse): editor language servers consume the JSON
 * Schema directly, not the Zod source. Validating with AJV here closes the
 * loop — we prove the JSON file an editor would download actually accepts
 * the YAML shapes opensquid expects. A Zod re-parse would prove Zod still
 * works (we already have schema unit tests for that), not that the emitted
 * JSON behaves the same way.
 *
 * Why a temp dir (not `schemas/`): the repo's `schemas/` is committed +
 * regenerated by `pnpm schemas`. If the test wrote there directly, a failing
 * test would leave stale files behind, and parallel test runs could clobber
 * each other. `node:os` tmpdir + a unique per-test subdir is hermetic.
 *
 * AJV strict mode: AJV's default strict mode warns on unknown keywords (e.g.
 * `default` is a documentation hint in draft-07 but not a validation rule).
 * We disable strict warnings — opensquid emits standards-compliant JSON
 * Schema, and we don't want test output cluttered with non-actionable warnings.
 */

import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import Ajv from 'ajv';
import { beforeAll, describe, expect, it } from 'vitest';

import { emitSchemas } from './emit-schemas.js';

const EXPECTED_FILES = [
  'channels.schema.json',
  'drift_response.schema.json',
  'manifest.schema.json',
  'models.schema.json',
  'notifications.schema.json',
  'skill.schema.json',
  'team.schema.json',
];

let outDir: string;
let written: string[];

beforeAll(async () => {
  outDir = await mkdtemp(join(tmpdir(), 'opensquid-schemas-'));
  written = await emitSchemas(outDir);
});

// ---------------------------------------------------------------------------
// Helper — load a schema file + compile an AJV validator for it.
//
// Each schema is self-contained (`$refStrategy: 'none'` in emit-schemas.ts),
// so a single-schema AJV instance per validator call is the right grain —
// no cross-schema $ref resolution to coordinate.
// ---------------------------------------------------------------------------

async function loadValidator(filename: string): Promise<(data: unknown) => boolean> {
  const raw = await readFile(join(outDir, filename), 'utf8');
  const parsed: unknown = JSON.parse(raw);
  const ajv = new Ajv({ strict: false, allErrors: true });
  // Ajv types declare `compile<T>` returning `ValidateFunction<T>`; we
  // collapse to a plain boolean predicate at this seam.
  const validate = ajv.compile(parsed as object);
  return (data: unknown) => validate(data) as boolean;
}

describe('emit-schemas — file emission', () => {
  it('writes all six expected schema files', () => {
    expect(written.map((p) => p.split('/').pop()).sort()).toEqual(EXPECTED_FILES);
  });

  it('every emitted file is valid JSON with the expected $ref + definitions shape', async () => {
    for (const f of EXPECTED_FILES) {
      const raw = await readFile(join(outDir, f), 'utf8');
      const parsed = JSON.parse(raw) as { $ref?: string; definitions?: Record<string, unknown> };
      expect(parsed.$ref).toMatch(/^#\/definitions\//);
      expect(parsed.definitions).toBeDefined();
    }
  });
});

// ---------------------------------------------------------------------------
// Manifest schema — the strictest of the six (`.strict()` in Zod → AJV
// `additionalProperties: false`). The two AJV checks below prove that
// round-trip: a minimum-viable pack passes; an uppercase name fails.
// ---------------------------------------------------------------------------

describe('manifest.schema.json — AJV validation', () => {
  it('accepts a minimum-viable pack', async () => {
    const validate = await loadValidator('manifest.schema.json');
    const ok = validate({
      name: 'p',
      version: '0.1.0',
      scope: 'workflow',
      goal: 'ship',
    });
    expect(ok).toBe(true);
  });

  it('rejects an uppercase name (regex enforces lowercase + hyphen)', async () => {
    const validate = await loadValidator('manifest.schema.json');
    const ok = validate({
      name: 'P',
      version: '0.1.0',
      scope: 'workflow',
      goal: 'ship',
    });
    expect(ok).toBe(false);
  });

  it('rejects a missing required field', async () => {
    const validate = await loadValidator('manifest.schema.json');
    const ok = validate({
      name: 'p',
      version: '0.1.0',
      scope: 'workflow',
      // missing goal
    });
    expect(ok).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Skill schema — permissive (no `.strict()` in Zod), but still enforces
// the required `name` field and the nested `rules[].process[].call` chain.
// ---------------------------------------------------------------------------

describe('skill.schema.json — AJV validation', () => {
  it('accepts a minimal skill with one rule + one process step', async () => {
    const validate = await loadValidator('skill.schema.json');
    const ok = validate({
      name: 'git',
      load: 'preload',
      rules: [
        {
          id: 'never-amend',
          process: [{ call: 'match_command', args: { pattern: 'x' } }],
        },
      ],
    });
    expect(ok).toBe(true);
  });

  it('rejects a skill missing the `name` field', async () => {
    const validate = await loadValidator('skill.schema.json');
    const ok = validate({ load: 'preload', rules: [] });
    expect(ok).toBe(false);
  });
});
